"""empty message

Revision ID: 5d6c8e7d8ca9
Revises: 
Create Date: 2023-04-10 14:30:40.637199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6c8e7d8ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commune', sa.String(length=50), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('age', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('medical_history', sa.String(length=500), nullable=False),
    sa.Column('is_adopted', sa.Boolean(), nullable=True),
    sa.Column('adress_id', sa.String(length=500), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('motivation', sa.String(length=500), nullable=False),
    sa.Column('style', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query1', sa.String(length=500), nullable=False),
    sa.Column('query2', sa.String(length=500), nullable=False),
    sa.Column('query3', sa.String(length=500), nullable=False),
    sa.Column('query4', sa.String(length=500), nullable=False),
    sa.Column('query5', sa.String(length=500), nullable=False),
    sa.Column('query6', sa.String(length=500), nullable=False),
    sa.Column('query7', sa.String(length=500), nullable=False),
    sa.Column('query8', sa.String(length=500), nullable=False),
    sa.Column('query9', sa.String(length=500), nullable=False),
    sa.Column('query10', sa.String(length=500), nullable=False),
    sa.Column('query11', sa.String(length=500), nullable=False),
    sa.Column('query12', sa.String(length=500), nullable=False),
    sa.Column('query13', sa.String(length=500), nullable=False),
    sa.Column('query14', sa.String(length=500), nullable=False),
    sa.Column('query15', sa.String(length=500), nullable=False),
    sa.Column('query16', sa.String(length=10), nullable=False),
    sa.Column('query17', sa.String(length=500), nullable=False),
    sa.Column('query18', sa.String(length=10), nullable=False),
    sa.Column('query19', sa.String(length=500), nullable=False),
    sa.Column('query20', sa.String(length=10), nullable=False),
    sa.Column('query21', sa.String(length=10), nullable=False),
    sa.Column('query22', sa.String(length=10), nullable=False),
    sa.Column('query23', sa.String(length=500), nullable=False),
    sa.Column('query24', sa.String(length=500), nullable=False),
    sa.Column('query25', sa.String(length=500), nullable=False),
    sa.Column('query26', sa.String(length=10), nullable=False),
    sa.Column('query27', sa.String(length=10), nullable=False),
    sa.Column('query28', sa.String(length=500), nullable=False),
    sa.Column('query29', sa.String(length=500), nullable=False),
    sa.Column('query30', sa.String(length=10), nullable=False),
    sa.Column('query31', sa.String(length=500), nullable=False),
    sa.Column('query32', sa.String(length=500), nullable=False),
    sa.Column('query33', sa.String(length=500), nullable=False),
    sa.Column('query34', sa.String(length=500), nullable=False),
    sa.Column('query35', sa.String(length=500), nullable=False),
    sa.Column('query36', sa.String(length=10), nullable=False),
    sa.Column('query37', sa.String(length=10), nullable=False),
    sa.Column('query38', sa.String(length=10), nullable=False),
    sa.Column('query39', sa.String(length=500), nullable=False),
    sa.Column('query40', sa.String(length=500), nullable=False),
    sa.Column('query41', sa.String(length=500), nullable=False),
    sa.Column('query42', sa.String(length=500), nullable=False),
    sa.Column('query43', sa.String(length=10), nullable=False),
    sa.Column('query44', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    op.drop_table('favorites')
    op.drop_table('description')
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('pet')
    op.drop_table('rol')
    op.drop_table('adress')
    # ### end Alembic commands ###
